// Generated by Haxe 4.2.2

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.orm.common.enums {
	public class DefaultTypeEnum : global::haxe.lang.Enum {
		
		protected DefaultTypeEnum(int index) : base(index) {
		}
		
		
		public static readonly global::nMorph.framework.orm.common.enums.DefaultTypeEnum DEFVARCHAR = new global::nMorph.framework.orm.common.enums.DefaultTypeEnum_DEFVARCHAR();
		
		public static readonly global::nMorph.framework.orm.common.enums.DefaultTypeEnum DEFINT = new global::nMorph.framework.orm.common.enums.DefaultTypeEnum_DEFINT();
		
		public static readonly global::nMorph.framework.orm.common.enums.DefaultTypeEnum DEFDOUBLE = new global::nMorph.framework.orm.common.enums.DefaultTypeEnum_DEFDOUBLE();
		
		public static readonly global::nMorph.framework.orm.common.enums.DefaultTypeEnum DEFDATE = new global::nMorph.framework.orm.common.enums.DefaultTypeEnum_DEFDATE();
		
		public static readonly global::nMorph.framework.orm.common.enums.DefaultTypeEnum DEFBOOL = new global::nMorph.framework.orm.common.enums.DefaultTypeEnum_DEFBOOL();
		
		protected static readonly string[] __hx_constructs = new string[]{"DEFVARCHAR", "DEFINT", "DEFDOUBLE", "DEFDATE", "DEFBOOL"};
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.orm.common.enums {
	public sealed class DefaultTypeEnum_DEFVARCHAR : global::nMorph.framework.orm.common.enums.DefaultTypeEnum {
		
		public DefaultTypeEnum_DEFVARCHAR() : base(0) {
		}
		
		
		public override string getTag() {
			return "DEFVARCHAR";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.orm.common.enums {
	public sealed class DefaultTypeEnum_DEFINT : global::nMorph.framework.orm.common.enums.DefaultTypeEnum {
		
		public DefaultTypeEnum_DEFINT() : base(1) {
		}
		
		
		public override string getTag() {
			return "DEFINT";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.orm.common.enums {
	public sealed class DefaultTypeEnum_DEFDOUBLE : global::nMorph.framework.orm.common.enums.DefaultTypeEnum {
		
		public DefaultTypeEnum_DEFDOUBLE() : base(2) {
		}
		
		
		public override string getTag() {
			return "DEFDOUBLE";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.orm.common.enums {
	public sealed class DefaultTypeEnum_DEFDATE : global::nMorph.framework.orm.common.enums.DefaultTypeEnum {
		
		public DefaultTypeEnum_DEFDATE() : base(3) {
		}
		
		
		public override string getTag() {
			return "DEFDATE";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.orm.common.enums {
	public sealed class DefaultTypeEnum_DEFBOOL : global::nMorph.framework.orm.common.enums.DefaultTypeEnum {
		
		public DefaultTypeEnum_DEFBOOL() : base(4) {
		}
		
		
		public override string getTag() {
			return "DEFBOOL";
		}
		
		
	}
}


