<?php
/**
 * Generated by Haxe 4.2.2
 */

namespace nMorph\framework\orm\common\ddl;

use \php\Boot;
use \nMorph\framework\orm\interfaces\IClause;
use \nMorph\framework\orm\tools\BulkRun;
use \nMorph\framework\common\exceptions\ExceptionHelper;
use \nMorph\framework\orm\client\QueryTable;
use \nMorph\framework\orm\client\QueueItem;
use \nMorph\framework\orm\lang\DDL;
use \nMorph\framework\orm\tools\Context;

class DropTableClause implements IClause {
	/**
	 * @var DDL
	 */
	public $CurrentDDL;
	/**
	 * @var string
	 */
	public $TableName;

	/**
	 * @param DDL $CurrentDDL
	 * @param string $TableName
	 * 
	 * @return void
	 */
	public function __construct ($CurrentDDL, $TableName) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:18: characters 9-37
		$this->CurrentDDL = $CurrentDDL;
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:19: characters 9-35
		$this->TableName = $TableName;
	}

	/**
	 * @param BulkRun $bulk
	 * 
	 * @return BulkRun
	 */
	public function Bulk ($bulk) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:57: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:58: characters 9-20
		return null;
	}

	/**
	 * @return mixed
	 */
	public function Execute () {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:44: characters 9-36
		return $this->CurrentDDL->Execute();
	}

	/**
	 * @param QueueItem[]|\Array_hx $queue
	 * 
	 * @return QueueItem[]|\Array_hx
	 */
	public function Queue ($queue) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:52: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:53: characters 9-20
		return null;
	}

	/**
	 * @param Class $cl
	 * @param Context $context
	 * 
	 * @return mixed[]|\Array_hx
	 */
	public function Read ($cl, $context = null) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:72: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:73: characters 9-20
		return null;
	}

	/**
	 * @param Class $cl
	 * @param Context $context
	 * 
	 * @return mixed
	 */
	public function ReadOne ($cl, $context = null) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:77: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:78: characters 9-20
		return null;
	}

	/**
	 * @return QueryTable
	 */
	public function ReadTable () {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:67: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:68: characters 9-20
		return null;
	}

	/**
	 * @return mixed
	 */
	public function ReadValue () {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:62: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:63: characters 9-20
		return null;
	}

	/**
	 * @param Context $context
	 * 
	 * @return void
	 */
	public function Register ($context) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:48: characters 9-62
		ExceptionHelper::LogicException(1, "Not Valid Method");
	}

	/**
	 * @return string
	 */
	public function SCRIPT () {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:40: characters 9-40
		return $this->CurrentDDL->GenerateAll();
	}

	/**
	 * @param string $args
	 * 
	 * @return void
	 */
	public function SCRIPT_PART ($args = null) {
		#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:24: characters 16-45
		$__hx__switch = ($this->CurrentDDL->getCurrentEngine()->index);
		if ($__hx__switch === 0) {
			#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:34: characters 17-70
			$this->CurrentDDL->AddBlock(" DROP TABLE \"" . ($this->TableName??'null') . "\" ");
		} else if ($__hx__switch === 1) {
			#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:30: characters 17-70
			$this->CurrentDDL->AddBlock(" DROP TABLE \"" . ($this->TableName??'null') . "\" ");
		} else if ($__hx__switch === 2) {
			#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:28: characters 17-70
			$this->CurrentDDL->AddBlock(" DROP TABLE \"" . ($this->TableName??'null') . "\" ");
		} else if ($__hx__switch === 3) {
			#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:32: characters 17-70
			$this->CurrentDDL->AddBlock(" DROP TABLE \"" . ($this->TableName??'null') . "\" ");
		} else if ($__hx__switch === 4) {
			#5_framework\orm\src/nMorph/framework/orm/common/ddl/DropTableClause.hx:26: characters 17-70
			$this->CurrentDDL->AddBlock(" DROP TABLE \"" . ($this->TableName??'null') . "\" ");
		}
	}
}

Boot::registerClass(DropTableClause::class, 'nMorph.framework.orm.common.ddl.DropTableClause');
