// Generated by Haxe 4.2.2
package hscript;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Interp_initOps_109__Fun extends haxe.lang.Function
{
	public Interp_initOps_109__Fun(hscript.Interp me)
	{
		//line 109 "C:\\HaxeToolkit\\haxe\\lib\\hscript\\2,5,0\\hscript\\Interp.hx"
		super(2, 0);
		//line 109 "C:\\HaxeToolkit\\haxe\\lib\\hscript\\2,5,0\\hscript\\Interp.hx"
		this.me = me;
	}
	
	
	@Override public java.lang.Object __hx_invoke2_o(double __fn_float1, java.lang.Object __fn_dyn1, double __fn_float2, java.lang.Object __fn_dyn2)
	{
		//line 109 "C:\\HaxeToolkit\\haxe\\lib\\hscript\\2,5,0\\hscript\\Interp.hx"
		java.lang.Object e2 = ( (( __fn_dyn2 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float2) )) : (((java.lang.Object) (__fn_dyn2) )) );
		//line 109 "C:\\HaxeToolkit\\haxe\\lib\\hscript\\2,5,0\\hscript\\Interp.hx"
		java.lang.Object e1 = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float1) )) : (((java.lang.Object) (__fn_dyn1) )) );
		//line 109 "C:\\HaxeToolkit\\haxe\\lib\\hscript\\2,5,0\\hscript\\Interp.hx"
		return haxe.lang.Runtime.eq(this.me.expr(e1), this.me.expr(e2));
	}
	
	
	public hscript.Interp me;
	
}


