<?php
/**
 * Generated by Haxe 4.2.2
 */

namespace nMorph\core\objects\ping;

use \php\Boot;

/**
 * ...
 * @author Smartwork
 */
class PingRequest {
	/**
	 * @var string
	 */
	static public $__rtti = "<class path=\"nMorph.core.objects.ping.PingRequest\" params=\"\">\x0A\x09<get_Name set=\"method\" line=\"17\"><f a=\"\"><c path=\"String\"/></f></get_Name>\x0A\x09<set_Name set=\"method\" line=\"22\"><f a=\"value\">\x0A\x09<c path=\"String\"/>\x0A\x09<c path=\"String\"/>\x0A</f></set_Name>\x0A\x09<Name public=\"1\" get=\"accessor\" set=\"accessor\">\x0A\x09\x09<c path=\"String\"/>\x0A\x09\x09<meta><m n=\":isVar\"/></meta>\x0A\x09</Name>\x0A\x09<new public=\"1\" set=\"method\" line=\"12\"><f a=\"\"><x path=\"Void\"/></f></new>\x0A\x09<haxe_doc>* ...\x0A * @author Smartwork</haxe_doc>\x0A\x09<meta>\x0A\x09\x09<m n=\":directlyUsed\"/>\x0A\x09\x09<m n=\":keepSub\"/>\x0A\x09\x09<m n=\":rtti\"/>\x0A\x09</meta>\x0A</class>";

	/**
	 * @var string
	 */
	public $Name;

	/**
	 * @return void
	 */
	public function __construct () {
	}

	/**
	 * @return string
	 */
	public function get_Name () {
		#2_logic\objects\src/nMorph/core/objects/ping/PingRequest.hx:18: characters 3-14
		return $this->Name;
	}

	/**
	 * @param string $value
	 * 
	 * @return string
	 */
	public function set_Name ($value) {
		#2_logic\objects\src/nMorph/core/objects/ping/PingRequest.hx:23: characters 3-22
		return $this->Name = $value;
	}
}

Boot::registerClass(PingRequest::class, 'nMorph.core.objects.ping.PingRequest');
Boot::registerGetters('nMorph\\core\\objects\\ping\\PingRequest', [
	'Name' => true
]);
Boot::registerSetters('nMorph\\core\\objects\\ping\\PingRequest', [
	'Name' => true
]);
