// Generated by Haxe 4.2.2
package nMorph.framework.orm.client;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class QueueItem extends haxe.lang.HxObject
{
	public QueueItem(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public QueueItem()
	{
		//line 4 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		nMorph.framework.orm.client.QueueItem.__hx_ctor_nMorph_framework_orm_client_QueueItem(this);
	}
	
	
	protected static void __hx_ctor_nMorph_framework_orm_client_QueueItem(nMorph.framework.orm.client.QueueItem __hx_this)
	{
	}
	
	
	public java.lang.String SQL;
	
	public haxe.root.Array<nMorph.framework.orm.client.QueryParameter> Parameters;
	
	public java.lang.String set_SQL(java.lang.String value)
	{
		//line 11 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		return this.SQL = value;
	}
	
	
	public java.lang.String get_SQL()
	{
		//line 15 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		return this.SQL;
	}
	
	
	public haxe.root.Array<nMorph.framework.orm.client.QueryParameter> get_Parameters()
	{
		//line 19 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		return this.Parameters;
	}
	
	
	public haxe.root.Array<nMorph.framework.orm.client.QueryParameter> set_Parameters(haxe.root.Array<nMorph.framework.orm.client.QueryParameter> value)
	{
		//line 23 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		return this.Parameters = value;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		{
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			if (( field != null )) 
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				switch (field.hashCode())
				{
					case -1842766326:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("Parameters")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							if (handleProperties) 
							{
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								this.set_Parameters(((haxe.root.Array<nMorph.framework.orm.client.QueryParameter>) (value) ));
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								return value;
							}
							else
							{
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								this.Parameters = ((haxe.root.Array<nMorph.framework.orm.client.QueryParameter>) (value) );
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								return value;
							}
							
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case 82350:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("SQL")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							if (handleProperties) 
							{
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								this.set_SQL(haxe.lang.Runtime.toString(value));
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								return value;
							}
							else
							{
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								this.SQL = haxe.lang.Runtime.toString(value);
								//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
								return value;
							}
							
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		{
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			if (( field != null )) 
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				switch (field.hashCode())
				{
					case -539359737:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("set_Parameters")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_Parameters")) );
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case 82350:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("SQL")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return ( (handleProperties) ? (this.get_SQL()) : (this.SQL) );
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case 1232376467:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("get_Parameters")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_Parameters")) );
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case -1842766326:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("Parameters")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return ( (handleProperties) ? (this.get_Parameters()) : (this.Parameters) );
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case -74816187:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("get_SQL")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_SQL")) );
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case 1985293393:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("set_SQL")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_SQL")) );
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		{
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			if (( field != null )) 
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				switch (field.hashCode())
				{
					case -539359737:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("set_Parameters")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return this.set_Parameters(((haxe.root.Array<nMorph.framework.orm.client.QueryParameter>) (dynargs[0]) ));
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case 1985293393:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("set_SQL")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return this.set_SQL(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case 1232376467:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("get_Parameters")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return this.get_Parameters();
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
					case -74816187:
					{
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						if (field.equals("get_SQL")) 
						{
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							__temp_executeDef1 = false;
							//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
							return this.get_SQL();
						}
						
						//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		baseArr.push("Parameters");
		//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		baseArr.push("SQL");
		//line 3 "C:\\TodoList\\nMorph\\5_framework\\orm\\src\\nMorph\\framework\\orm\\client\\QueueItem.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


