<?php
/**
 * Generated by Haxe 4.2.2
 */

namespace hscript;

use \php\Boot;

class Completion {
	/**
	 * @var object
	 */
	public $expr;
	/**
	 * @var TType
	 */
	public $t;

	/**
	 * @param object $expr
	 * @param TType $t
	 * 
	 * @return void
	 */
	public function __construct ($expr, $t) {
		#C:\HaxeToolkit\haxe\lib\hscript/2,5,0/hscript/Checker.hx:82: characters 3-19
		$this->expr = $expr;
		#C:\HaxeToolkit\haxe\lib\hscript/2,5,0/hscript/Checker.hx:83: characters 3-13
		$this->t = $t;
	}
}

Boot::registerClass(Completion::class, 'hscript.Completion');
