/**
 * Kendo UI v2023.2.606 (http://www.telerik.com/kendo-ui)
 * Copyright 2023 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.html.base.js";import"./kendo.icons.js";var __meta__={id:"html.chip",name:"Html.Chip",category:"web",description:"HTML rendering utility for Kendo UI for jQuery.",depends:["html.base","icons"],features:[]};!function(e,a){var s=window.kendo,t=s.html.HTMLBase,i=t.extend({init:function(e,a){t.fn.init.call(this,e,a),this._wrapper()},options:{name:"HTMLChip",size:"medium",rounded:"medium",fillMode:"solid",themeColor:"base",attr:{},icon:"",iconClass:"",iconAttr:{},removable:!1,removableAttr:{},removeIcon:"x-circle",removeIconClass:"",content:"",text:"",stylingOptions:["size","rounded","fillMode","themeColor"]},_wrapper:function(){var a=this,t=a.options;t.text=t.text||t.label,a.wrapper=a.element.wrap("<div class='k-chip'></div>").parent().attr(t.attr),a._addClasses(),t.icon?a.wrapper.prepend(e(s.ui.icon({icon:t.icon,size:"small",iconClass:"k-chip-icon"+(t.iconClass?` ${t.iconClass}`:"")})).attr(t.iconAttr)):t.iconClass?a.wrapper.prepend(e("<span class='"+t.iconClass+"'></span>").attr(t.iconAttr)):t.avatarClass&&a.wrapper.prepend(e("<span class='k-chip-avatar k-avatar "+t.avatarClass+"'></span>").attr(t.iconAttr)),a.element.addClass("k-chip-content"),t.text&&a.element.html('<span class="k-chip-label">'+t.text+"</span>"),!1===t.visible&&a.wrapper.addClass("k-hidden"),!0===t.selected&&a.wrapper.addClass("k-selected"),!1===t.enabled&&a.wrapper.addClass("k-disabled"),t.removable&&a.wrapper.append(e(`<span class='k-chip-action k-chip-remove-action'>${s.ui.icon({icon:t.removeIcon,iconClass:"k-chip-icon"})}</span>`).attr(t.removableAttr))}});e.extend(s.html,{renderChip:function(a,s){return a&&!e.isPlainObject(a)||(s=a,a=e("<span></span>")),new i(a,s).html()},HTMLChip:i}),s.cssProperties.registerPrefix("HTMLChip","k-chip-"),s.cssProperties.registerValues("HTMLChip",[{prop:"rounded",values:s.cssProperties.roundedValues.concat([["full","full"]])}])}(window.kendo.jQuery);
//# sourceMappingURL=kendo.html.chip.js.map
