// Generated by Haxe 4.2.2
package nMorph.framework.common.helpers;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class UUIDKEY extends haxe.lang.HxObject
{
	public UUIDKEY(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public UUIDKEY()
	{
		//line 2 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		nMorph.framework.common.helpers.UUIDKEY.__hx_ctor_nMorph_framework_common_helpers_UUIDKEY(this);
	}
	
	
	protected static void __hx_ctor_nMorph_framework_common_helpers_UUIDKEY(nMorph.framework.common.helpers.UUIDKEY __hx_this)
	{
	}
	
	
	public static java.lang.String uuid()
	{
		//line 5 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		haxe.root.StringBuf uid = new haxe.root.StringBuf();
		//line 5 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		int a = 8;
		//line 6 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		uid.add(haxe.lang.Runtime.toString(haxe.root.StringTools.hex(((int) (((double) (haxe.root.Date.now().date.getTimeInMillis()) )) ), 8)));
		//line 6 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
		//line 7 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		while (( a++ < 36 ))
		{
			//line 8 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
			uid.add(haxe.lang.Runtime.toString(( (( (( ( a * 51 ) & 52 )) != 0 )) ? (haxe.root.StringTools.hex(( (( (( a ^ 15 )) != 0 )) ? (( 8 ^ ((int) (( java.lang.Math.random() * (( (( (( a ^ 20 )) != 0 )) ? (16) : (4) )) )) ) )) : (4) ), null)) : ("-") )));
			//line 8 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
			java.lang.Object __temp_expr2 = ((java.lang.Object) (null) );
		}
		
		//line 13 "C:\\TodoList\\nMorph\\5_framework\\common\\src\\nMorph\\framework\\common\\helpers\\UUIDKEY.hx"
		return uid.toString().toLowerCase();
	}
	
	
}


