// Generated by Haxe 4.2.2

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.common.configuration {
	public class ConfigurationData : global::haxe.lang.HxObject {
		
		public ConfigurationData(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ConfigurationData() {
			global::nMorph.framework.common.configuration.ConfigurationData.__hx_ctor_nMorph_framework_common_configuration_ConfigurationData(this);
		}
		
		
		protected static void __hx_ctor_nMorph_framework_common_configuration_ConfigurationData(global::nMorph.framework.common.configuration.ConfigurationData __hx_this) {
		}
		
		
		public string LogFolder;
		
		public global::nMorph.framework.common.configuration.DeployEnvironmentEnum CurrentDeployEnvironment;
		
		public virtual string get_LogFolder() {
			return this.LogFolder;
		}
		
		
		public virtual string set_LogFolder(string @value) {
			return this.LogFolder = @value;
		}
		
		
		public virtual global::nMorph.framework.common.configuration.DeployEnvironmentEnum get_CurrentDeployEnvironment() {
			return this.CurrentDeployEnvironment;
		}
		
		
		public virtual global::nMorph.framework.common.configuration.DeployEnvironmentEnum set_CurrentDeployEnvironment(global::nMorph.framework.common.configuration.DeployEnvironmentEnum @value) {
			return this.CurrentDeployEnvironment = @value;
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 744358035:
					{
						if (handleProperties) {
							this.set_CurrentDeployEnvironment(((global::nMorph.framework.common.configuration.DeployEnvironmentEnum) (@value) ));
							return @value;
						}
						else {
							this.CurrentDeployEnvironment = ((global::nMorph.framework.common.configuration.DeployEnvironmentEnum) (@value) );
							return @value;
						}
						
					}
					
					
					case 1439849010:
					{
						if (handleProperties) {
							this.set_LogFolder(global::haxe.lang.Runtime.toString(@value));
							return @value;
						}
						else {
							this.LogFolder = global::haxe.lang.Runtime.toString(@value);
							return @value;
						}
						
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1893491216:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_CurrentDeployEnvironment", 1893491216)) );
					}
					
					
					case 1840387740:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_CurrentDeployEnvironment", 1840387740)) );
					}
					
					
					case 1547440149:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_LogFolder", 1547440149)) );
					}
					
					
					case 389426697:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_LogFolder", 389426697)) );
					}
					
					
					case 744358035:
					{
						return ( (handleProperties) ? (this.get_CurrentDeployEnvironment()) : (this.CurrentDeployEnvironment) );
					}
					
					
					case 1439849010:
					{
						return ( (handleProperties) ? (this.get_LogFolder()) : (this.LogFolder) );
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1893491216:
					{
						return this.set_CurrentDeployEnvironment(((global::nMorph.framework.common.configuration.DeployEnvironmentEnum) (dynargs[0]) ));
					}
					
					
					case 1840387740:
					{
						return this.get_CurrentDeployEnvironment();
					}
					
					
					case 1547440149:
					{
						return this.set_LogFolder(global::haxe.lang.Runtime.toString(dynargs[0]));
					}
					
					
					case 389426697:
					{
						return this.get_LogFolder();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			baseArr.push("CurrentDeployEnvironment");
			baseArr.push("LogFolder");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


