// Generated by Haxe 4.2.2

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace nMorph.framework.common.helpers {
	public class Int64_Helper : global::haxe.lang.HxObject {
		
		static Int64_Helper() {
			global::nMorph.framework.common.helpers.Int64_Helper.MAX_32_PRECISION = 4294967296.0;
		}
		
		
		public Int64_Helper(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Int64_Helper() {
			global::nMorph.framework.common.helpers.Int64_Helper.__hx_ctor_nMorph_framework_common_helpers_Int64_Helper(this);
		}
		
		
		protected static void __hx_ctor_nMorph_framework_common_helpers_Int64_Helper(global::nMorph.framework.common.helpers.Int64_Helper __hx_this) {
		}
		
		
		public static double MAX_32_PRECISION;
		
		public static long fromFloat(double f) {
			unchecked {
				int h = ((int) (( f / 4294967296.0 )) );
				int l = ((int) (f) );
				long this1 = ( ( ((long) (h) ) << 32 ) | ( ((long) (l) ) & 0xffffffffL ) );
				return ((long) (this1) );
			}
		}
		
		
		public static double toFloat(long i) {
			unchecked {
				double f = ((double) (((int) (((long) (i) )) )) );
				if (( f < 0 )) {
					f += 4294967296.0;
				}
				
				return ( ( (((int) (( ((long) (i) ) >> 32 )) )) * 4294967296.0 ) + f );
			}
		}
		
		
	}
}


